services:
  backend_rds:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION:-us-east-1}.amazonaws.com/yefp1/backend-rds:${BACKEND_RDS_TAG:-latest}
    restart: unless-stopped
    user: appuser
    cap_drop:
      - ALL
    security_opt:
      - "no-new-privileges=true"
    read_only: true
    tmpfs:
      - /tmp
    environment:
      - CORS_ALLOWED_ORIGINS=${API_CORS_ALLOWED_ORIGINS}
      - DEBUG=${API_DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    secrets:
      - db_password
      - secret_key
      # - django_superuser_email
      # - django_superuser_username
      # - django_superuser_password
    ports:
      - "8000:8000"
    networks:
       - app
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8000/test_connection/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

secrets:
  db_password:
    file: /home/ubuntu/backend_rds/db_password
  secret_key:
    file: /home/ubuntu/backend_rds/django_secret_key
  # django_superuser_email:
  #   file: /home/ubuntu/backend_rds/django_superuser_email
  # django_superuser_username:
  #   file: /home/ubuntu/backend_rds/django_superuser_username
  # django_superuser_password:
  #   file: /home/ubuntu/backend_rds/django_superuser_password

networks:
    app:
